par=demand_overrides rng=NodeDemandOvrd!A2 rDim=4 

par=offer_parameter_overrides rng=OfferParameterOvrd!A2 rDim=3 

par=energy_offer_overrides rng=EnergyOfferOvrd!A2 rDim=4 

par=reserve_offer_overrides rng=ReserveOfferOvrd!A2 rDim=6

par=bid_parameter_overrides rng=BidParameterOvrd!A2 rDim=3

par=energy_bid_overrides rng=EnergyBidOvrd!A2 rDim=4 

par=branch_parameter_overrides rng=BranchParameterOvrd!A2 rDim=3 

par=branch_constraint_overrides rng=BranchConstraintOvrd!A2 rDim=3 

par=branch_cnstr_factor_overrides rng=BranchConstraintFactorOvrd!A2 rDim=3 

par=marketnode_constraint_overrides rng=MnodeConstraintOvrd!A2 rDim=3 

par=marketnode_cnstr_factor_overrides rng=MnodeConstraintFactorOvrd!A2 rDim=5 


