$inlinecom ## ## 
$eolcom ! 
 
$setglobal runName               Test_20140211
 
$setglobal programPath           '%system.fp%'
$setglobal inputPath             '%system.fp%..\Input\'
$setglobal ovrdPath              '%system.fp%..\Override\'
$setglobal outputPath            '%system.fp%..\Output\'
 
$setglobal licenseMode           0
$setglobal vSPDinputFileName     'vSPDrunFile'              ! Name of Excel run file when using the Excel interface
$setglobal vSPDinputOvrdData     'overridesFromExcel'       ! Name of override file when using EMI
