$inlinecom ## ## 
$eolcom ! 
 
$setglobal runName               'FP_20150115_F'
 
$setglobal programPath           '%system.fp%'
$setglobal inputPath             '%system.fp%..\Input\'
$setglobal ovrdPath              '%system.fp%..\Override\'
$setglobal outputPath            '%system.fp%..\Output\'
 
$setglobal licenseMode           1
$setglobal vSPDinputFileName     'vSPDrunFile'              ! Name of Excel run file when using the Excel interface
$setglobal vSPDinputOvrdData     'overridesv1'       ! Name of override file when using EMI

