$ONTEXT
a. to solve all trading periods
/  
All
/  

b. to solve trading periods 3 and 6
/                /        
TP3      Or      TP3, TP6 
TP6              /        
/                         
$OFFTEXT
*============================================= // ==========================================

/ 
TP1
TP2
TP3
TP4
TP5
TP6
TP7
TP8
TP9
TP10
TP11
TP12
TP13
TP14
TP15
TP16
TP17
TP18
TP19
TP20
TP21
TP22
TP23
TP24
TP25
TP26
TP27
TP28
TP29
TP30
TP31
TP32
TP33
TP34
TP35
TP36
TP37
TP38
TP39
TP40
TP41
TP42
TP43
TP44
TP45
TP46
TP47
TP48
TP49
TP50
/ 