$setglobal runName      base_emi_test
$setglobal licenseMode  0
 
$setglobal programPath  C:\vSPD\vSPD_v1.4\base\vSPD_1.4\Programs_v1.4_v1\
$setglobal inputPath    C:\vSPD\vSPD_v1.4\base\vSPD_1.4\Programs_v1.4_v1\..\Input\
$setglobal outputPath   C:\vSPD\vSPD_v1.4\base\vSPD_1.4\Programs_v1.4_v1\..\Output\
$setglobal ovrdPath     C:\vSPD\vSPD_v1.4\base\vSPD_1.4\Programs_v1.4_v1\..\Override\
 
* Name of Excel run file when in Excel mode
$setglobal vSPDinputFileName    'vSPDrunFile'
* Name of override file when run in emi
$setglobal vSPDinputOvrdData    'ara2201_maxlimit'
