$setglobal    runName     Test
$setglobal    Mode        0
 
$setglobal    ProgramPath     /home/humed/vSPD/Programs/
$setglobal    InputPath       /home/humed/vSPD/Input/
$setglobal    OvrdPath        /home/humed/vSPD/Programs/
$setglobal    OutputPath      /home/humed/vSPD/Output/
 
$setglobal       VSPDInputOvrdData      'VSPDRunFile'
$setglobal       VSPDInputOvrdFormat    2
$setglobal       VSPDInputFileName      'VSPDRunFile'
